<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO8ZISL8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO8ZISL8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO8ZISL8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO8ZISL8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerO8ZISL8\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'O8ZISL8',
    'container.build_id' => 'b1894e50',
    'container.build_time' => 1528383751,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerO8ZISL8');
