<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'routing.loader' shared service.

$a = ($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService());
$b = ($this->services['kernel'] ?? $this->get('kernel'));

$c = new \Sensio\Bundle\FrameworkExtraBundle\Routing\AnnotatedRouteControllerLoader($a);

$d = new \Symfony\Component\HttpKernel\Config\FileLocator($b, ($this->targetDirs[3].'/src/Resources'), array(0 => ($this->targetDirs[3].'/src')));

$e = new \Symfony\Bundle\FrameworkBundle\Routing\AnnotatedRouteControllerLoader($a);

$f = new \Symfony\Component\Config\Loader\LoaderResolver();
$f->addLoader($c);
$f->addLoader(new \Symfony\Component\Routing\Loader\AnnotationDirectoryLoader($d, $c));
$f->addLoader(new \Symfony\Component\Routing\Loader\AnnotationFileLoader($d, $c));
$f->addLoader(new \Symfony\Component\Routing\Loader\XmlFileLoader($d));
$f->addLoader(new \Symfony\Component\Routing\Loader\YamlFileLoader($d));
$f->addLoader(new \Symfony\Component\Routing\Loader\PhpFileLoader($d));
$f->addLoader(new \Symfony\Component\Routing\Loader\GlobFileLoader($d));
$f->addLoader(new \Symfony\Component\Routing\Loader\DirectoryLoader($d));
$f->addLoader(new \Symfony\Component\Routing\Loader\DependencyInjection\ServiceRouterLoader($this));
$f->addLoader($e);
$f->addLoader(new \Symfony\Component\Routing\Loader\AnnotationDirectoryLoader($d, $e));
$f->addLoader(new \Symfony\Component\Routing\Loader\AnnotationFileLoader($d, $e));

return $this->services['routing.loader'] = new \Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader(($this->privates['controller_name_converter'] ?? $this->privates['controller_name_converter'] = new \Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser($b)), $f);
